begin;

create schema if not exists app_auth;

revoke all on schema app_auth from public;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists app_auth.roles (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists app_auth.permissions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists app_auth.role_permissions (
  role_id bigint not null references app_auth.roles (id) on delete cascade,
  permission_id bigint not null references app_auth.permissions (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists app_auth.user_roles (
  user_id uuid not null references auth.users (id) on delete cascade,
  role_id bigint not null references app_auth.roles (id) on delete cascade,
  assigned_by uuid references auth.users (id),
  assigned_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function app_auth.authorize(requested_permission text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    return false;
  end if;

  return exists (
    select 1
    from app_auth.user_roles ur
    join app_auth.role_permissions rp on rp.role_id = ur.role_id
    join app_auth.permissions p on p.id = rp.permission_id
    join public.profiles pr on pr.id = ur.user_id
    where ur.user_id = current_user_id
      and pr.is_active = true
      and p.key = requested_permission
  );
end;
$$;

create or replace function public.my_permissions()
returns table (permission_key text)
language sql
stable
security definer
set search_path = ''
as $$
  select distinct p.key
  from app_auth.user_roles ur
  join app_auth.role_permissions rp on rp.role_id = ur.role_id
  join app_auth.permissions p on p.id = rp.permission_id
  join public.profiles pr on pr.id = ur.user_id
  where ur.user_id = auth.uid()
    and pr.is_active = true
  order by p.key;
$$;

create or replace function public.admin_list_users()
returns table (
  user_id uuid,
  email text,
  full_name text,
  is_active boolean,
  roles text[]
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    u.id as user_id,
    u.email::text as email,
    p.full_name,
    p.is_active,
    coalesce(array_agg(distinct r.key) filter (where r.key is not null), '{}') as roles
  from auth.users u
  join public.profiles p on p.id = u.id
  left join app_auth.user_roles ur on ur.user_id = u.id
  left join app_auth.roles r on r.id = ur.role_id
  where app_auth.authorize('usuarios.read')
  group by u.id, u.email, p.full_name, p.is_active
  order by u.email asc;
$$;

create or replace function public.admin_assign_role(target_user_id uuid, role_key text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_role_id bigint;
begin
  if not app_auth.authorize('usuarios.manage') then
    raise exception 'not_allowed';
  end if;

  select id into target_role_id
  from app_auth.roles
  where key = role_key;

  if target_role_id is null then
    raise exception 'role_not_found';
  end if;

  insert into app_auth.user_roles (user_id, role_id, assigned_by)
  values (target_user_id, target_role_id, auth.uid())
  on conflict do nothing;
end;
$$;

create or replace function public.admin_remove_role(target_user_id uuid, role_key text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_role_id bigint;
begin
  if not app_auth.authorize('usuarios.manage') then
    raise exception 'not_allowed';
  end if;

  select id into target_role_id
  from app_auth.roles
  where key = role_key;

  if target_role_id is null then
    raise exception 'role_not_found';
  end if;

  delete from app_auth.user_roles
  where user_id = target_user_id
    and role_id = target_role_id;
end;
$$;

insert into app_auth.roles (key, name, description)
values
  ('admin', 'Administrador', 'Acesso total ao sistema'),
  ('gerente', 'Gerente', 'Acompanha operação e gestão'),
  ('recepcao', 'Recepção', 'Opera reservas e atendimento'),
  ('financeiro', 'Financeiro', 'Opera confirmações financeiras')
on conflict (key) do update
set
  name = excluded.name,
  description = excluded.description;

insert into app_auth.permissions (key, description)
values
  ('reservas.read', 'Ler reservas'),
  ('reservas.create', 'Criar reservas'),
  ('reservas.update', 'Editar reservas'),
  ('reservas.cancel', 'Cancelar reservas'),
  ('reservas.checkin', 'Confirmar presença'),
  ('reservas.no_show', 'Marcar no-show'),
  ('pagamentos.read', 'Ler pagamentos'),
  ('pagamentos.confirm', 'Confirmar pagamentos'),
  ('usuarios.read', 'Listar usuários'),
  ('usuarios.manage', 'Gerenciar roles e acessos')
on conflict (key) do update
set description = excluded.description;

with role_permission_map as (
  select 'admin'::text as role_key, 'reservas.read'::text as permission_key union all
  select 'admin', 'reservas.create' union all
  select 'admin', 'reservas.update' union all
  select 'admin', 'reservas.cancel' union all
  select 'admin', 'reservas.checkin' union all
  select 'admin', 'reservas.no_show' union all
  select 'admin', 'pagamentos.read' union all
  select 'admin', 'pagamentos.confirm' union all
  select 'admin', 'usuarios.read' union all
  select 'admin', 'usuarios.manage' union all
  select 'gerente', 'reservas.read' union all
  select 'gerente', 'reservas.create' union all
  select 'gerente', 'reservas.update' union all
  select 'gerente', 'reservas.cancel' union all
  select 'gerente', 'reservas.checkin' union all
  select 'gerente', 'reservas.no_show' union all
  select 'gerente', 'pagamentos.read' union all
  select 'gerente', 'pagamentos.confirm' union all
  select 'gerente', 'usuarios.read' union all
  select 'recepcao', 'reservas.read' union all
  select 'recepcao', 'reservas.create' union all
  select 'recepcao', 'reservas.update' union all
  select 'recepcao', 'reservas.cancel' union all
  select 'recepcao', 'reservas.checkin' union all
  select 'recepcao', 'reservas.no_show' union all
  select 'financeiro', 'pagamentos.read' union all
  select 'financeiro', 'pagamentos.confirm' union all
  select 'financeiro', 'reservas.read'
)
insert into app_auth.role_permissions (role_id, permission_id)
select r.id, p.id
from role_permission_map m
join app_auth.roles r on r.key = m.role_key
join app_auth.permissions p on p.key = m.permission_key
on conflict do nothing;

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own_or_manage" on public.profiles;
create policy "profiles_select_own_or_manage"
on public.profiles
for select
to authenticated
using (
  (select auth.uid()) = id
  or (select app_auth.authorize('usuarios.read'))
);

drop policy if exists "profiles_update_own_or_manage" on public.profiles;
create policy "profiles_update_own_or_manage"
on public.profiles
for update
to authenticated
using (
  (select auth.uid()) = id
  or (select app_auth.authorize('usuarios.manage'))
)
with check (
  (select auth.uid()) = id
  or (select app_auth.authorize('usuarios.manage'))
);

grant usage on schema app_auth to authenticated;
grant execute on function app_auth.authorize(text) to authenticated;
grant execute on function public.my_permissions() to authenticated;
grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_assign_role(uuid, text) to authenticated;
grant execute on function public.admin_remove_role(uuid, text) to authenticated;

revoke all on all tables in schema app_auth from anon, authenticated;
revoke execute on function public.my_permissions() from public;
revoke execute on function public.admin_list_users() from public;
revoke execute on function public.admin_assign_role(uuid, text) from public;
revoke execute on function public.admin_remove_role(uuid, text) from public;

commit;
