begin;

create schema if not exists app_auth;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists app_auth.roles (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists app_auth.permissions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists app_auth.role_permissions (
  role_id bigint not null references app_auth.roles (id) on delete cascade,
  permission_id bigint not null references app_auth.permissions (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists app_auth.user_roles (
  user_id uuid not null references auth.users (id) on delete cascade,
  role_id bigint not null references app_auth.roles (id) on delete cascade,
  assigned_by uuid references auth.users (id),
  assigned_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function app_auth.authorize(requested_permission text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    return false;
  end if;

  return exists (
    select 1
    from app_auth.user_roles ur
    join app_auth.role_permissions rp on rp.role_id = ur.role_id
    join app_auth.permissions p on p.id = rp.permission_id
    join public.profiles pr on pr.id = ur.user_id
    where ur.user_id = current_user_id
      and pr.is_active = true
      and p.key = requested_permission
  );
end;
$$;

create or replace function public.my_permissions()
returns table (permission_key text)
language sql
stable
security definer
set search_path = ''
as $$
  select distinct p.key
  from app_auth.user_roles ur
  join app_auth.role_permissions rp on rp.role_id = ur.role_id
  join app_auth.permissions p on p.id = rp.permission_id
  join public.profiles pr on pr.id = ur.user_id
  where ur.user_id = auth.uid()
    and pr.is_active = true
  order by p.key;
$$;

insert into app_auth.roles (key, name, description)
values
  ('admin', 'Administrador', 'Acesso total'),
  ('gerente', 'Gerente', 'Gestao operacional'),
  ('recepcao', 'Recepcao', 'Operacao de reservas'),
  ('financeiro', 'Financeiro', 'Operacao financeira'),
  ('visualizacao', 'Visualizacao', 'Apenas leitura')
on conflict (key) do update
set name = excluded.name, description = excluded.description;

insert into app_auth.permissions (key, description)
values
  ('reservas.read', 'Ler reservas'),
  ('reservas.create', 'Criar reservas'),
  ('reservas.update', 'Editar reservas'),
  ('reservas.cancel', 'Cancelar reservas'),
  ('reservas.checkin', 'Confirmar presença'),
  ('reservas.no_show', 'Marcar no-show'),
  ('reservas.delete', 'Excluir reservas'),
  ('reservas.change_date', 'Alterar data da reserva'),
  ('pagamentos.read', 'Ler pagamentos'),
  ('pagamentos.confirm', 'Confirmar pagamentos')
on conflict (key) do update
set description = excluded.description;

-- Limpar mapeamentos existentes para evitar permissões residuais antigas
delete from app_auth.role_permissions;

with role_permission_map as (
  -- admin
  select 'admin'::text as role_key, 'reservas.read'::text as permission_key union all
  select 'admin', 'reservas.create' union all
  select 'admin', 'reservas.update' union all
  select 'admin', 'reservas.change_date' union all
  select 'admin', 'reservas.cancel' union all
  select 'admin', 'reservas.checkin' union all
  select 'admin', 'reservas.no_show' union all
  select 'admin', 'reservas.delete' union all
  select 'admin', 'pagamentos.read' union all
  select 'admin', 'pagamentos.confirm' union all
  -- gerente
  select 'gerente', 'reservas.read' union all
  select 'gerente', 'reservas.checkin' union all
  select 'gerente', 'reservas.no_show' union all
  -- recepcao
  
  select 'recepcao', 'reservas.create' union all
  select 'recepcao', 'reservas.update' union all
  select 'recepcao', 'reservas.read' union all
  select 'recepcao', 'reservas.change_date' union all
  select 'recepcao', 'reservas.cancel' union all
  -- visualizacao
  select 'visualizacao', 'reservas.read' union all
  -- financeiro
  select 'financeiro', 'reservas.read' union all
  select 'financeiro', 'pagamentos.read' union all
  select 'financeiro', 'pagamentos.confirm'
)
insert into app_auth.role_permissions (role_id, permission_id)
select r.id, p.id
from role_permission_map m
join app_auth.roles r on r.key = m.role_key
join app_auth.permissions p on p.key = m.permission_key
on conflict do nothing;

grant usage on schema app_auth to authenticated;
grant execute on function app_auth.authorize(text) to authenticated;
grant execute on function public.my_permissions() to authenticated;

alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
      and table_name = 'reservas'
  ) then
    execute 'grant select, insert, update, delete on public.reservas to authenticated';
    execute 'alter table public.reservas enable row level security';

    execute 'drop policy if exists reservas_select_policy on public.reservas';
    execute $sql$
      create policy reservas_select_policy
      on public.reservas
      for select
      to authenticated
      using ((select app_auth.authorize('reservas.read')))
    $sql$;

    execute 'drop policy if exists reservas_insert_policy on public.reservas';
    execute $sql$
      create policy reservas_insert_policy
      on public.reservas
      for insert
      to authenticated
      with check ((select app_auth.authorize('reservas.create')))
    $sql$;

    execute 'drop policy if exists reservas_update_policy on public.reservas';
    execute $sql$
      create policy reservas_update_policy
      on public.reservas
      for update
      to authenticated
      using (
        (select app_auth.authorize('reservas.update'))
        or (select app_auth.authorize('reservas.checkin'))
        or (select app_auth.authorize('reservas.no_show'))
        or (select app_auth.authorize('reservas.cancel'))
        or (select app_auth.authorize('reservas.change_date'))
      )
      with check (
        (select app_auth.authorize('reservas.update'))
        or (select app_auth.authorize('reservas.checkin'))
        or (select app_auth.authorize('reservas.no_show'))
        or (select app_auth.authorize('reservas.cancel'))
        or (select app_auth.authorize('reservas.change_date'))
      )
    $sql$;

    execute 'drop policy if exists reservas_delete_policy on public.reservas';
    execute $sql$
      create policy reservas_delete_policy
      on public.reservas
      for delete
      to authenticated
      using ((select app_auth.authorize('reservas.delete')))
    $sql$;
  end if;
end
$$;

commit;
